name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Generate parser
        run: tree-sitter generate
      - name: Verify that generated parser matches the repository
        run: |
          diff=`git diff HEAD -- src`
          echo "$diff"
          test -z "$diff"
      - name: Run tests
        run: tree-sitter test --show-fields
      - name: Set up examples
        run: |-
          git clone https://github.com/square/okhttp.git examples/okhttp --single-branch --depth=1 --filter=blob:none   
          git clone https://github.com/ktorio/ktor.git examples/ktor --single-branch --depth=1 --filter=blob:none   
          git clone https://github.com/square/leakcanary.git examples/leakcanary --single-branch --depth=1 --filter=blob:none   
          git clone https://github.com/JetBrains/compose-multiplatform.git examples/compose-multiplatform --single-branch --depth=1 --filter=blob:none   
          git clone https://github.com/Kotlin/kotlinx.coroutines.git examples/kotlinx.coroutines --single-branch --depth=1 --filter=blob:none   
          git clone https://github.com/pinterest/ktlint examples/ktlint --single-branch --depth=1 --filter=blob:none   
          git clone https://github.com/microsoft/thrifty examples/thrifty --single-branch --depth=1 --filter=blob:none 
      - name: Parse examples
        id: examples
        continue-on-error: true
        uses: tree-sitter/parse-action@v4
        with:
          files: examples/**/*.kt          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build and test crate
        run: cargo test
